# Generated by Django 3.0.5 on 2020-04-02 23:06

import board.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=5000)),
                ('type', models.CharField(choices=[('sell', 'Sprzedam'), ('buy', 'Kupię'), ('barter', 'Zamienię')], default='sell', max_length=6)),
                ('category', models.CharField(choices=[('flower', 'Susz'), ('seed', 'Nasiona'), ('fiber', 'Włókna i paździerze')], default='seed', max_length=6)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, help_text='Jeden lub więcej plików', null=True, upload_to=board.models.user_dir_path)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='board.Advert')),
            ],
        ),
    ]
