# Generated by Django 3.0.4 on 2020-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='type',
            field=models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy'), ('barter', 'Exchange')], default='sell', max_length=6),
        ),
    ]
