# Generated by Django 3.0.4 on 2020-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_advert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(max_length=200),
        ),
    ]
