# Generated by Django 3.0.4 on 2020-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200329_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('flower', 'Susz'), ('seed', 'Nasiona'), ('fiber', 'Włókna i paździerze')], default='seed', max_length=6),
        ),
        migrations.AlterField(
            model_name='advert',
            name='type',
            field=models.CharField(choices=[('sell', 'Sprzedam'), ('buy', 'Kupię'), ('barter', 'Zamienię')], default='sell', max_length=6),
        ),
    ]
