# Generated by Django 3.0.4 on 2020-03-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200329_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='ziomek1', max_length=30),
            preserve_default=False,
        ),
    ]
