# Generated by Django 3.0.4 on 2020-03-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='id',
        ),
        migrations.AddField(
            model_name='advert',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=123, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.User'),
            preserve_default=False,
        ),
    ]
