# Generated by Django 3.0.4 on 2020-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20200330_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='advert',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
