# Generated by Django 3.0.4 on 2020-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20200330_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='creator',
            field=models.ManyToManyField(to='board.User'),
        ),
    ]
