# Generated by Django 3.0.4 on 2020-03-30 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_advert_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='creator',
        ),
        migrations.AddField(
            model_name='advert',
            name='creator',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='board.User'),
            preserve_default=False,
        ),
    ]
