# Generated by Django 3.0.4 on 2020-03-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20200330_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='upload',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
