# Generated by Django 3.0.4 on 2020-03-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_advert_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
