# Generated by Django 3.0.4 on 2020-03-31 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20200331_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='upload',
        ),
    ]
