# Generated by Django 3.0.4 on 2020-03-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20200331_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertfile',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
