# Generated by Django 3.0.4 on 2020-03-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_auto_20200331_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertfile',
            old_name='feed',
            new_name='advert',
        ),
    ]
