# Generated by Django 3.0.4 on 2020-03-31 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_auto_20200331_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertfile',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='board.Advert'),
        ),
    ]
