# Generated by Django 3.0.4 on 2020-03-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_auto_20200331_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertfile',
            name='advert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='board.Advert'),
        ),
        migrations.AlterField(
            model_name='advertfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
