# Generated by Django 3.0.4 on 2020-04-01 10:34

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20200331_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=board.models.user_dir_path),
        ),
    ]
