# Generated by Django 3.0.4 on 2020-04-02 14:59

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_auto_20200401_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertfile',
            name='file',
            field=models.ImageField(blank=True, help_text='Jeden lub więcej plików', null=True, upload_to=board.models.user_dir_path),
        ),
    ]
