# Generated by Django 3.0.4 on 2020-04-02 15:07

import board.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_auto_20200402_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertfile',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Jeden lub więcej plików', null=True, upload_to=board.models.user_dir_path),
        ),
    ]
