version: '3.7'

services:
  djangoapp:
    build: .
    container_name: zbyt_board
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static
      - upload_volume:/opt/services/djangoapp/photos
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    container_name: zbyt_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/error.log:/etc/nginx/error_log.log
      - static_volume:/opt/services/djangoapp/static
      - upload_volume:/opt/services/djangoapp/photos
      - ./config/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  upload_volume:
